Repository Groot-94/ios-diary, pull requests merged in 2022-08, with the labels that each got.

#2 Feat 1 json model
  Diary.xcodeproj/project.pbxproj
  Diary/Base.lproj/Main.storyboard
  Diary/Info.plist
  Diary/Resources/AppDelegate.swift
  Diary/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Diary/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Diary/Resources/Assets.xcassets/Contents.json
  Diary/Resources/Assets.xcassets/testSample.dataset/Contents.json
  Diary/Resources/Assets.xcassets/testSample.dataset/sample.json
  Diary/Resources/Base.lproj/LaunchScreen.storyboard
  Diary/Resources/SceneDelegate.swift
  Diary/TestModel/DiaryTestData.swift
  Diary/ViewController.swift
  DiaryTests/DiaryTests.swift
Labels: feat, test

#3 feat: DiaryListViewController생성 및 SceneDelegate연결
  Diary.xcodeproj/project.pbxproj
  Diary/Resources/SceneDelegate.swift
  Diary/Scene/DiaryList/DiaryListViewController.swift
Labels: feat

#4 feat: DiaryTableViewCell 구현
  Diary.xcodeproj/project.pbxproj
  Diary/Scene/DiaryList/View/DiaryTableViewCell.swift
Labels: feat

#5 Feat 4 diary list table view controller
  .swiftlint.yml
  Diary.xcodeproj/project.pbxproj
  Diary.xcodeproj/xcshareddata/xcschemes/Diary.xcscheme
  Diary/Scene/DiaryList/Controller/DiaryListViewController.swift
  Diary/Scene/DiaryList/DiaryListViewController.swift
  Diary/Scene/DiaryList/Model/DummyData.swift
  Diary/Scene/DiaryList/View/DiaryTableViewCell.swift
  Diary/TestModel/DiaryTestData.swift
  Diary/extension/Double+extension.swift
Labels: feat, style

#6 Feat 5 diary detail view controller
  Diary.xcodeproj/project.pbxproj
  Diary/Scene/DiaryDetail/View/DiaryDetailView.swift
  Diary/Scene/DiaryList/Controller/DiaryListViewController.swift
  Diary/extension/DiaryDetailViewController.swift
  Diary/protocol/DataSendable.swift
Labels: feat

#7 Step1 refactor
  Diary/Scene/DiaryDetail/View/DiaryDetailView.swift
  Diary/Scene/DiaryList/Controller/DiaryListViewController.swift
  Diary/Scene/DiaryList/View/DiaryTableViewCell.swift
  Diary/extension/DiaryDetailViewController.swift
Labels: refactor, fix

#8 Step1 refactor
  Diary.xcodeproj/project.pbxproj
  Diary/Resources/AppDelegate.swift
  Diary/Scene/DiaryDetail/Controller/DiaryDetailViewController.swift
  Diary/Scene/DiaryDetail/View/DiaryDetailView.swift
  Diary/Scene/DiaryList/Controller/DiaryListViewController.swift
  Diary/Scene/DiaryList/Model/DummyData.swift
  Diary/Scene/DiaryList/Model/MockData.swift
  Diary/TestModel/DiaryModel.swift
  Diary/protocol/DiaryDataManagerProtocol.swift
  DiaryTests/DiaryTests.swift
Labels: refactor, feat

#9 Step1 refactor
  Diary.xcodeproj/project.pbxproj
  Diary/Scene/DiaryDetail/Controller/DiaryDetailViewController.swift
  Diary/Scene/DiaryDetail/View/DiaryDetailView.swift
  Diary/Scene/DiaryList/Controller/DiaryListViewController.swift
  Diary/Scene/DiaryList/Model/DiaryDataManager.swift
  Diary/Scene/DiaryList/Model/MockData.swift
  Diary/protocol/DataSendable.swift
  Pods/Pods.xcodeproj/project.pbxproj
Labels: refactor, fix

#10 Feat 6 core data model
  CoreDataManager.swift
  Diary+CoreDataClass.swift
  Diary+CoreDataProperties.swift
  Diary.xcodeproj/project.pbxproj
  Diary/Diary.xcdatamodeld/Diary.xcdatamodel/contents
  DiaryModel.swift
Labels: feat

#11 Feat 7 diary register view controller
  Diary.xcodeproj/project.pbxproj
  Diary/Resources/SceneDelegate.swift
  Diary/Scene/DiaryList/Controller/DiaryListViewController.swift
  Diary/Scene/DiaryList/Model/DiaryData.swift
  Diary/Scene/DiaryList/Model/DiaryDataManager.swift
  Diary/Scene/DiaryRegister/Controller/DiaryRegisterViewController.swift
  Diary/Scene/DiaryRegister/View/DiaryRegisterView.swift
Labels: feat

#12 Feat 8 UI alert conrtoller
  Diary.xcodeproj/project.pbxproj
  Diary/Resources/SceneDelegate.swift
  Diary/Scene/DiaryDetail/Controller/DiaryDetailViewController.swift
  Diary/Scene/DiaryDetail/View/DiaryDetailView.swift
Labels: feat

#13 feat: DiaryListViewController 공유, 삭제 기능 추가
  Diary.xcodeproj/project.pbxproj
  Diary/Scene/DiaryDetail/Controller/DiaryDetailViewController.swift
  Diary/Scene/DiaryList/Controller/DiaryListViewController.swift
  Diary/Scene/DiaryRegister/Controller/DiaryRegisterViewController.swift
Labels: feat

#14 Step2 refactor
  CoreDataManager.swift
  Diary+CoreDataProperties.swift
  Diary.xcodeproj/project.pbxproj
  Diary/Scene/DiaryDetail/Controller/DiaryDetailViewController.swift
  Diary/Scene/DiaryList/Controller/DiaryListViewController.swift
  Diary/Scene/DiaryRegister/Controller/DiaryRegisterViewController.swift
Labels: refactor, fix

#15 Step2 refactor
  CoreDataManager.swift
  Diary+CoreDataClass.swift
  Diary.xcodeproj/project.pbxproj
  Diary/Resources/AppDelegate.swift
  Diary/Resources/SceneDelegate.swift
  Diary/Scene/DiaryDetail/Controller/DiaryDetailViewController.swift
  Diary/Scene/DiaryDetail/View/DiaryDetailView.swift
  Diary/Scene/DiaryList/Controller/DiaryListViewController.swift
  Diary/Scene/DiaryRegister/Controller/DiaryRegisterViewController.swift
  Diary/Scene/DiaryRegister/View/DiaryRegisterView.swift
Labels: refactor
